using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CborSerialization.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class CborSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all partial class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(cls => cls != null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) => GenerateSource(spc, source.Left, source.Right));
    }

    private void GenerateSource(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes)
    {
        // Diagnostic: generator running
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor(
                "CBORGEN001", "CBOR Generator", "CBOR source generator running. Found {0} partial classes.", "Debug", DiagnosticSeverity.Info, true),
            Location.None, classes.Length));

        var cborSerializableAttributeSymbol = compilation.GetTypeByMetadataName("CborSerialization.CborSerializableAttribute");
        if (cborSerializableAttributeSymbol == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBORGEN002", "CBOR Generator", "Could not find CborSerializableAttribute.", "Error", DiagnosticSeverity.Error, true),
                Location.None));
            return;
        }

        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var typeSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (typeSymbol == null)
                continue;

            // Only process context classes with [CborSerializable] attributes
            var serializableAttributes = typeSymbol.GetAttributes()
                .Where(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, cborSerializableAttributeSymbol))
                .ToList();

            if (!serializableAttributes.Any())
                continue;

            // Diagnostic: found context class
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBORGEN003", "CBOR Generator", "Generating context for {0}", "Debug", DiagnosticSeverity.Info, true),
                Location.None, typeSymbol.Name));

            var source = GenerateContextSource(typeSymbol, serializableAttributes);
            
            // Diagnostic: show generated code
            var lines = source.Split('\n');
            for (int i = 0; i < lines.Length; i++)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CBORGEN004", "CBOR Generator", "Line {0}: {1}", "Debug", DiagnosticSeverity.Info, true),
                    Location.None, i + 1, lines[i].TrimEnd()));
            }

            context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateContextSource(INamedTypeSymbol contextType, List<AttributeData> serializableAttributes)
    {
        var builder = new StringBuilder();
        var namespaceName = contextType.ContainingNamespace.IsGlobalNamespace ? null : contextType.ContainingNamespace.ToDisplayString();

        // Add diagnostic comment
        builder.AppendLine("// Generated by CborSourceGenerator. This file should only contain the context class with Default, GetTypeInfo<T>(), and type info properties.");
        builder.AppendLine();

        // Add using statements
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Formats.Cbor;");
        builder.AppendLine("using CborSerialization;");
        builder.AppendLine();

        // Add namespace (block-scoped)
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
        }

        // Add partial class declaration
        builder.AppendLine($"public partial class {contextType.Name}");
        builder.AppendLine("{");

        // Add Default property
        builder.AppendLine($"    public static {contextType.Name} Default {{ get; }} = new {contextType.Name}();");
        builder.AppendLine();

        // Add GetTypeInfo implementation
        builder.AppendLine("    public override CborTypeInfo<T> GetTypeInfo<T>()");
        builder.AppendLine("    {");
        builder.AppendLine("        return typeof(T) switch");
        builder.AppendLine("        {");

        foreach (var attr in serializableAttributes)
        {
            if (attr.ConstructorArguments.Length == 0)
                continue;
            var typeArg = attr.ConstructorArguments[0];
            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
                continue;
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyName(typeSymbol);
            builder.AppendLine($"            Type t when t == typeof({typeName}) => (CborTypeInfo<T>)(object){propertyName},");
        }

        builder.AppendLine("            _ => throw new ArgumentException($\"Type {typeof(T)} is not registered for serialization\")");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        // Add type info properties for each serializable type
        foreach (var attr in serializableAttributes)
        {
            if (attr.ConstructorArguments.Length == 0)
                continue;
            var typeArg = attr.ConstructorArguments[0];
            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
                continue;
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    public CborTypeInfo<{typeName}> {propertyName} {{ get; }}");
        }

        // Add constructor to initialize type info properties with 'this'
        builder.AppendLine($"    public {contextType.Name}()");
        builder.AppendLine("    {");
        foreach (var attr in serializableAttributes)
        {
            if (attr.ConstructorArguments.Length == 0)
                continue;
            var typeArg = attr.ConstructorArguments[0];
            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
                continue;
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"        {propertyName} = new {propertyName}TypeInfo(this);");
        }
        builder.AppendLine("    }");

        // Add type info implementations for each serializable type
        foreach (var attr in serializableAttributes)
        {
            if (attr.ConstructorArguments.Length == 0)
                continue;
            var typeArg = attr.ConstructorArguments[0];
            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
                continue;
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    private sealed class {propertyName}TypeInfo : CborTypeInfo<{typeName}>");
            builder.AppendLine("    {");
            builder.AppendLine($"        private readonly {contextType.Name} _context;");
            builder.AppendLine($"        public {propertyName}TypeInfo({contextType.Name} context) => _context = context;");
            builder.AppendLine($"        public override void Serialize(CborWriter writer, {typeName} value)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateSerializationCode(typeSymbol, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine($"        public override {typeName} Deserialize(CborReader reader)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateDeserializationCode(typeSymbol, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}"); // close class
        if (!string.IsNullOrEmpty(namespaceName))
            builder.AppendLine("}"); // close namespace

        return builder.ToString();
    }

    private static string GetPropertyName(INamedTypeSymbol typeSymbol)
    {
        var name = typeSymbol.Name;
        int backtickIndex = name.IndexOf('`');
        if (typeSymbol.IsGenericType)
        {
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            // Use 'Of' to join type arguments for uniqueness and readability
            name += "Of" + string.Join("And", typeSymbol.TypeArguments.Select(t => GetPropertyNameFromType(t)));
        }
        else if (backtickIndex >= 0)
        {
            name = name.Substring(0, backtickIndex);
        }
        return name;
    }

    private static string GetPropertyNameFromType(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            int backtickIndex = name.IndexOf('`');
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            name += "Of" + string.Join("And", namedType.TypeArguments.Select(t => GetPropertyNameFromType(t)));
            return name;
        }
        else if (typeSymbol is INamedTypeSymbol namedType2)
        {
            var name = namedType2.Name;
            int backtickIndex = name.IndexOf('`');
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            return name;
        }
        return typeSymbol.Name;
    }
}