namespace CbOrSerialization.Generator;

internal enum CbOrKnownNamingPolicy
{
    Unspecified = 0,
    CamelCase = 1,
    SnakeCaseLower = 2,
    SnakeCaseUpper = 3,
    KebabCaseLower = 4,
    KebabCaseUpper = 5,
    UpperCase = 6,
    LowerCase = 7
}

[Generator(LanguageNames.CSharp)]
public sealed class CbOrSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all partial class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(cls => cls != null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) => GenerateSource(spc, source.Left, source.Right));
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes)
    {
        // Diagnostic: generator running
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor(
                "CBOR001", "CbOr Generator", "CbOr source generator running. Found {0} partial classes.", "Debug", DiagnosticSeverity.Info, true),
            Location.None, classes.Length));

        var cbOrSerializableAttributeSymbol = compilation.GetTypeByMetadataName("CbOrSerialization.CbOrSerializableAttribute");
        if (cbOrSerializableAttributeSymbol == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBOR002", "CbOr Generator", "Could not find CbOrSerializableAttribute.", "Error", DiagnosticSeverity.Error, true),
                Location.None));
            return;
        }

        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var typeSymbol = model.GetDeclaredSymbol(classDecl);
            if (typeSymbol == null)
                continue;

            // Only process context classes with [CborSerializable] attributes
            var serializableAttributes = typeSymbol.GetAttributes()
                .Where(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, cbOrSerializableAttributeSymbol))
                .ToImmutableArray();

            if (!serializableAttributes.Any())
                continue;

            // Diagnostic: found context class
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBOR003", "CbOr Generator", "Generating context for {0}", "Debug", DiagnosticSeverity.Info, true),
                Location.None, typeSymbol.Name));

            var source = GenerateContextSource(typeSymbol, serializableAttributes);

            // Diagnostic: show generated code
            var lines = source.Split('\n');
            for (int i = 0; i < lines.Length; i++)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CBOR004", "CbOr Generator", "Line {0}: {1}", "Debug", DiagnosticSeverity.Info, true),
                    Location.None, i + 1, lines[i].TrimEnd()));
            }

            context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateContextSource(INamedTypeSymbol contextType, ImmutableArray<AttributeData> serializableAttributes)
    {
        var builder = new StringBuilder();
        var namingPolicy = GetNamingPolicy(contextType);
        var namespaceName = contextType.ContainingNamespace.IsGlobalNamespace ? null : contextType.ContainingNamespace.ToDisplayString();

        // Add diagnostic comment
        builder.AppendLine("// Generated by CbOrSourceGenerator. This file should only contain the context class with Default, GetTypeInfo<T>(), and type info properties.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Add using statements
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Formats.Cbor;");
        builder.AppendLine("using CbOrSerialization;");
        builder.AppendLine();

        // Add namespace (block-scoped)
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
        }

        // Add partial class declaration
        builder.AppendLine($"public partial class {contextType.Name}");
        builder.AppendLine("{");

        // Add Default property
        builder.AppendLine($"    public static {contextType.Name} Default {{ get; }} = new {contextType.Name}();");
        builder.AppendLine();

        // Add GetTypeInfo implementation
        builder.AppendLine("    public override CbOrTypeInfo<T> GetTypeInfo<T>()");
        builder.AppendLine("    {");
        builder.AppendLine("        return typeof(T) switch");
        builder.AppendLine("        {");

        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyName(typeSymbol);
            builder.AppendLine($"            Type t when t == typeof({typeName}) => (CbOrTypeInfo<T>)(object){propertyName},");
        }

        builder.AppendLine("            _ => throw new ArgumentException($\"Type {typeof(T)} is not registered for serialization\")");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        // Add type info properties for each serializable type
        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    public CbOrTypeInfo<{typeName}> {propertyName} {{ get; }}");
        }

        // Add constructor to initialize type info properties with 'this'
        builder.AppendLine($"    public {contextType.Name}()");
        builder.AppendLine("    {");

        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
            {
                continue;
            }

            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"        {propertyName} = new {propertyName}TypeInfo(this);");
        }

        builder.AppendLine("    }");

        // Add type info implementations for each serializable type
        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not INamedTypeSymbol typeSymbol)
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    private sealed class {propertyName}TypeInfo : CbOrTypeInfo<{typeName}>");
            builder.AppendLine("    {");
            builder.AppendLine($"        private readonly {contextType.Name} _context;");
            builder.AppendLine($"        public {propertyName}TypeInfo({contextType.Name} context) => _context = context;");
            builder.AppendLine($"        public override void Serialize(CborWriter writer, {typeName} value)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateSerializationCode(typeSymbol, namingPolicy, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine($"        public override {typeName} Deserialize(CborReader reader)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateDeserializationCode(typeSymbol, namingPolicy, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        // Add nullable helper methods
        GenerateNullableHelpers(builder);

        builder.AppendLine("}"); // close class
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine("}"); // close namespace
        }

        return builder.ToString();
    }

    private static void GenerateNullableHelpers(StringBuilder builder)
    {
        var primitiveTypes = new[]
        {
            ("Int32", "ReadInt32"),
            ("Boolean", "ReadBoolean"),
            ("String", "ReadTextString"),
            ("Double", "ReadDouble"),
            ("Single", "ReadSingle"),
            ("Int64", "ReadInt64"),
            ("UInt32", "ReadUInt32"),
            ("UInt64", "ReadUInt64"),
            ("Byte", "ReadUInt32"),
            ("SByte", "ReadInt32"),
            ("Int16", "ReadInt32"),
            ("UInt16", "ReadUInt32"),
            ("Guid", "ReadByteString")
        };

        foreach (var (typeName, readerMethod) in primitiveTypes)
        {
            var castPrefix = typeName switch
            {
                "Byte" => "(byte)",
                "SByte" => "(sbyte)",
                "Int16" => "(short)",
                "UInt16" => "(ushort)",
                _ => ""
            };

            builder.AppendLine($"    private static {typeName}? ReadNullable{typeName}(CborReader reader)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (reader.PeekState() == CborReaderState.Null)");
            builder.AppendLine("        {");
            builder.AppendLine("            reader.ReadNull();");
            builder.AppendLine("            return null;");
            builder.AppendLine("        }");
            
            if (typeName == "Guid")
            {
                builder.AppendLine("        return new System.Guid(reader.ReadByteString());");
            }
            else
            {
                builder.AppendLine($"        return {castPrefix}reader.{readerMethod}();");
            }
            
            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    private static string GetPropertyName(INamedTypeSymbol typeSymbol)
    {
        var name = typeSymbol.Name;
        int backtickIndex = name.IndexOf('`');
        if (typeSymbol.IsGenericType)
        {
            if (backtickIndex >= 0)
            {
                name = name.Substring(0, backtickIndex);
            }

            // Use 'Of' to join type arguments for uniqueness and readability
            name += "Of" + string.Join("And", typeSymbol.TypeArguments.Select(GetPropertyNameFromType));
        }
        else if (backtickIndex >= 0)
        {
            name = name.Substring(0, backtickIndex);
        }

        return name;
    }

    private static string GetPropertyNameFromType(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            int backtickIndex = name.IndexOf('`');
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            name += "Of" + string.Join("And", namedType.TypeArguments.Select(GetPropertyNameFromType));
            return name;
        }
        else if (typeSymbol is INamedTypeSymbol namedType2)
        {
            var name = namedType2.Name;
            int backtickIndex = name.IndexOf('`');
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            return name;
        }

        return typeSymbol.Name;
    }

    private static CbOrKnownNamingPolicy GetNamingPolicy(INamedTypeSymbol contextType)
    {
        var attr = contextType.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "CbOrSerialization.CbOrSourceGenerationOptionsAttribute");

        if (attr != null)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "PropertyNamingPolicy" && arg.Value.Value is int val)
                    return (CbOrKnownNamingPolicy)val;
            }
        }

        return CbOrKnownNamingPolicy.Unspecified;
    }
}

