namespace NCbor.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class NCborSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all partial class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(cls => cls != null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) => GenerateSource(spc, source.Left, source.Right));
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes)
    {
        // Diagnostic: generator running
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor(
                "CBOR001", "NCbor Generator", "NCbor source generator running. Found {0} partial classes.", "Debug", DiagnosticSeverity.Info, true),
            Location.None, classes.Length));

        var cbOrSerializableAttributeSymbol = compilation.GetTypeByMetadataName("NCbor.NCborSerializableAttribute");
        if (cbOrSerializableAttributeSymbol == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBOR002", "NCbor Generator", "Could not find NCborSerializableAttribute.", "Error", DiagnosticSeverity.Error, true),
                Location.None));
            return;
        }

        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var typeSymbol = model.GetDeclaredSymbol(classDecl);
            if (typeSymbol == null)
                continue;

            // Only process context classes with [CborSerializable] attributes
            var serializableAttributes = typeSymbol.GetAttributes()
                .Where(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, cbOrSerializableAttributeSymbol))
                .ToImmutableArray();

            if (!serializableAttributes.Any())
                continue;

            // Diagnostic: found context class
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CBOR003", "NCbor Generator", "Generating context for {0}", "Debug", DiagnosticSeverity.Info, true),
                Location.None, typeSymbol.Name));

            var source = GenerateContextSource(typeSymbol, serializableAttributes);

            // Diagnostic: show generated code
            var lines = source.Split('\n');
            for (int i = 0; i < lines.Length; i++)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CBOR004", "NCbor Generator", "Line {0}: {1}", "Debug", DiagnosticSeverity.Info, true),
                    Location.None, i + 1, lines[i].TrimEnd()));
            }

            context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateContextSource(INamedTypeSymbol contextType, ImmutableArray<AttributeData> serializableAttributes)
    {
        var builder = new StringBuilder();
        var namingPolicy = GetNamingPolicy(contextType);
        var namespaceName = contextType.ContainingNamespace.IsGlobalNamespace ? null : contextType.ContainingNamespace.ToDisplayString();

        // Add diagnostic comment
        builder.AppendLine("// Generated by NCborSourceGenerator. This file should only contain the context class with Default, GetTypeInfo<T>(), and type info properties.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Add using statements
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Formats.Cbor;");
        builder.AppendLine("using NCbor;");
        builder.AppendLine();

        // Add namespace (block-scoped)
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
        }

        // Add partial class declaration
        builder.AppendLine($"public partial class {contextType.Name}");
        builder.AppendLine("{");

        // Add Default property
        builder.AppendLine($"    public static {contextType.Name} Default {{ get; }} = new {contextType.Name}();");
        builder.AppendLine();

        // Add GetTypeInfo implementation
        builder.AppendLine("    public override NCborTypeInfo<T> GetTypeInfo<T>()");
        builder.AppendLine("    {");
        builder.AppendLine("        return typeof(T) switch");
        builder.AppendLine("        {");

        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not ITypeSymbol typeSymbol)
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyName(typeSymbol);
            builder.AppendLine($"            Type t when t == typeof({typeName}) => (NCborTypeInfo<T>)(object){propertyName},");
        }

        builder.AppendLine("            _ => throw new ArgumentException($\"Type {typeof(T)} is not registered for serialization\")");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        // Add type info properties for each serializable type
        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not ITypeSymbol typeSymbol)
            {
                continue;
            }

            // Skip built-in types and nullable built-in types - they don't need context properties
            if (IsBuiltInType(typeSymbol) || IsNullableBuiltInType(typeSymbol))
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    public NCborTypeInfo<{typeName}> {propertyName} {{ get; }}");
        }

        // Add constructor to initialize type info properties with 'this'
        builder.AppendLine($"    public {contextType.Name}()");
        builder.AppendLine("    {");

        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not ITypeSymbol typeSymbol)
            {
                continue;
            }

            // Skip built-in types and nullable built-in types - they don't need context properties
            if (IsBuiltInType(typeSymbol) || IsNullableBuiltInType(typeSymbol))
            {
                continue;
            }

            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"        {propertyName} = new {propertyName}TypeInfo(this);");
        }

        builder.AppendLine("    }");

        // Add type info implementations for each serializable type
        foreach (var args in serializableAttributes.Select(x => x.ConstructorArguments))
        {
            if (args.Length == 0)
            {
                continue;
            }

            var typeArg = args[0];

            if (typeArg.Value is not ITypeSymbol typeSymbol)
            {
                continue;
            }

            // Skip built-in types and nullable built-in types - they don't need context properties
            if (IsBuiltInType(typeSymbol) || IsNullableBuiltInType(typeSymbol))
            {
                continue;
            }

            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var propertyName = GetPropertyNameFromType(typeSymbol);
            builder.AppendLine($"    private sealed class {propertyName}TypeInfo : NCborTypeInfo<{typeName}>");
            builder.AppendLine("    {");
            builder.AppendLine($"        private readonly {contextType.Name} _context;");
            builder.AppendLine($"        public {propertyName}TypeInfo({contextType.Name} context) => _context = context;");
            builder.AppendLine($"        public override void Serialize(CborWriter writer, {typeName} value)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateSerializationCode(typeSymbol, namingPolicy, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine($"        public override {typeName} Deserialize(CborReader reader)");
            builder.AppendLine("        {");
            builder.AppendLine(SerializationCodeGenerator.GenerateDeserializationCode(typeSymbol, namingPolicy, "_context"));
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        // Add nullable helper methods
        GenerateNullableHelpers(builder);

        builder.AppendLine("}"); // close class
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine("}"); // close namespace
        }

        return builder.ToString();
    }

    private static void GenerateNullableHelpers(StringBuilder builder)
    {
        var primitiveTypes = new[]
        {
            ("Int32", "ReadInt32"),
            ("Boolean", "ReadBoolean"),
            ("String", "ReadTextString"),
            ("Double", "ReadDouble"),
            ("Single", "ReadSingle"),
            ("Int64", "ReadInt64"),
            ("UInt32", "ReadUInt32"),
            ("UInt64", "ReadUInt64"),
            ("Byte", "ReadUInt32"),
            ("SByte", "ReadInt32"),
            ("Int16", "ReadInt32"),
            ("UInt16", "ReadUInt32"),
            ("Decimal", "ReadDecimal"),
            ("Guid", "ReadByteString"),
            ("DateTime", "ReadTextString"),
            ("DateTimeOffset", "ReadTextString")
        };

        foreach (var (typeName, readerMethod) in primitiveTypes)
        {
            var castPrefix = typeName switch
            {
                "Byte" => "(byte)",
                "SByte" => "(sbyte)",
                "Int16" => "(short)",
                "UInt16" => "(ushort)",
                _ => ""
            };

            builder.AppendLine($"    private static {typeName}? ReadNullable{typeName}(CborReader reader)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (reader.PeekState() == CborReaderState.Null)");
            builder.AppendLine("        {");
            builder.AppendLine("            reader.ReadNull();");
            builder.AppendLine("            return null;");
            builder.AppendLine("        }");
            
            if (typeName == "Guid")
            {
                builder.AppendLine("        return new System.Guid(reader.ReadByteString());");
            }
            else if (typeName == "DateTime")
            {
                builder.AppendLine("        return System.DateTime.ParseExact(reader.ReadTag() == System.Formats.Cbor.CborTag.DateTimeString ? reader.ReadTextString() : throw new System.InvalidOperationException(\"Expected DateTimeString tag\"), \"yyyy-MM-ddTHH:mm:ss.FFFFFFFK\", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.RoundtripKind);");
            }
            else if (typeName == "DateTimeOffset")
            {
                builder.AppendLine("        return System.DateTimeOffset.ParseExact(reader.ReadTag() == System.Formats.Cbor.CborTag.DateTimeString ? reader.ReadTextString() : throw new System.InvalidOperationException(\"Expected DateTimeString tag\"), \"yyyy-MM-ddTHH:mm:ss.FFFFFFFK\", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.RoundtripKind);");
            }
            else
            {
                builder.AppendLine($"        return {castPrefix}reader.{readerMethod}();");
            }
            
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        // Add helper method for reading null values
        builder.AppendLine("    private static T? ReadNullValue<T>(CborReader reader) where T : class");
        builder.AppendLine("    {");
        builder.AppendLine("        reader.ReadNull();");
        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine();
        
        // Add helper method for reading null enum values
        builder.AppendLine("    private static T? ReadNullEnum<T>(CborReader reader) where T : struct, System.Enum");
        builder.AppendLine("    {");
        builder.AppendLine("        reader.ReadNull();");
        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string GetPropertyName(ITypeSymbol typeSymbol)
    {
        // Delegate to GetPropertyNameFromType for consistency
        return GetPropertyNameFromType(typeSymbol);
    }

    private static string GetPropertyNameFromType(ITypeSymbol typeSymbol)
    {
        // Handle arrays
        if (typeSymbol is IArrayTypeSymbol arrayType)
        {
            return $"ArrayOf{GetPropertyNameFromType(arrayType.ElementType)}";
        }
        
        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            int backtickIndex = name.IndexOf('`');
            if (backtickIndex >= 0)
                name = name.Substring(0, backtickIndex);
            name += "Of" + string.Join("And", namedType.TypeArguments.Select(GetPropertyNameFromType));
            return name;
        }
        
        // Handle built-in types specially - they don't need context references
        var specialTypeName = typeSymbol.SpecialType switch
        {
            SpecialType.System_String => "String",
            SpecialType.System_Int32 => "Int32", 
            SpecialType.System_Boolean => "Boolean",
            SpecialType.System_Double => "Double",
            SpecialType.System_Single => "Single",
            SpecialType.System_Int64 => "Int64",
            SpecialType.System_UInt32 => "UInt32",
            SpecialType.System_UInt64 => "UInt64",
            SpecialType.System_Byte => "Byte",
            SpecialType.System_SByte => "SByte",
            SpecialType.System_Int16 => "Int16",
            SpecialType.System_UInt16 => "UInt16",
            _ => null
        };
        
        if (specialTypeName != null) return specialTypeName;
        
        // Handle other built-in types
        var displayString = typeSymbol.ToDisplayString();
        if (displayString == "System.Guid")
        {
            return "Guid";
        }
        
        if (displayString == "System.DateTime")
        {
            return "DateTime";
        }
        
        if (displayString == "System.DateTimeOffset")
        {
            return "DateTimeOffset";
        }
        
        if (displayString == "System.Decimal" || displayString == "decimal")
        {
            return "Decimal";
        }
        
        return typeSymbol.Name;
    }

    private static bool IsBuiltInType(ITypeSymbol typeSymbol)
    {
        // byte[] is a built-in type - uses CBOR byte string directly, no context property needed
        if (typeSymbol is IArrayTypeSymbol arrayType && arrayType.ElementType.SpecialType == SpecialType.System_Byte)
        {
            return true;
        }

        // Other arrays are NOT built-in types - they need context properties
        if (typeSymbol is IArrayTypeSymbol)
        {
            return false;
        }
        
        // Handle special types
        var isSpecialType = typeSymbol.SpecialType switch
        {
            SpecialType.System_String => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_Boolean => true,
            SpecialType.System_Double => true,
            SpecialType.System_Single => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_UInt32 => true,
            SpecialType.System_UInt64 => true,
            SpecialType.System_Byte => true,
            SpecialType.System_SByte => true,
            SpecialType.System_Int16 => true,
            SpecialType.System_UInt16 => true,
            _ => false
        };
        
        if (isSpecialType) return true;
        
        // Handle enums - they serialize as their underlying type
        if (typeSymbol.TypeKind == TypeKind.Enum)
        {
            return true;
        }
        
        // Handle other built-in types (not SpecialTypes)
        var displayString = typeSymbol.ToDisplayString();
        return displayString == "System.Guid" ||
               displayString == "System.DateTime" ||
               displayString == "System.DateTimeOffset" ||
               displayString == "System.Decimal" ||
               displayString == "decimal";
    }

    private static bool IsNullableBuiltInType(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType && 
            namedType.Name == "Nullable" && namedType.TypeArguments.Length == 1)
        {
            var underlyingType = namedType.TypeArguments[0];
            return IsBuiltInType(underlyingType);
        }
        return false;
    }

    private static NCborNamingPolicy GetNamingPolicy(INamedTypeSymbol contextType)
    {
        var attr = contextType.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "NCbor.NCborSourceGenerationOptionsAttribute");

        if (attr != null)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "PropertyNamingPolicy" && arg.Value.Value is int val)
                    return (NCborNamingPolicy)val;
            }
        }

        return NCborNamingPolicy.Unspecified;
    }
}
